import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'
import Input from '../components/Input'
import Temperatures from '../components/Temperatures'

export default function Home() {
  const [loading, setLoading] = useState(false)
  const [data, setData] = useState(null)
  const [location, setLocation] = useState({
    city: '',
    country: 'GB',
  })

  const fetchData = async () => { 
    const res = await fetch(`https://api.openweathermap.org/data/2.5/forecast?q=${location.city},${location.country}&appid=${process.env.NEXT_PUBLIC_ENV_LOCAL_VARIABLE}`)
    const data = await res.json()
    setData(data)
    setLoading(false)
  }

  const handleSubmit = (e: { preventDefault: () => void }) => {
    e.preventDefault()
    setLoading(true)
    fetchData()
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Input handleSubmit={handleSubmit} setLocation={setLocation} />
        {data && (
          <Temperatures data={data} />
        )}
      </main>
    </>
  )
}
